project_id = "verdact-dev"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]
